
export const APP_MANIFEST = {
  progman: {
    type: "progman",
    title: "Program Manager",
    width: 500,
    height: 480,
    icon: "progman",
    label: "Program Manager",
    showInProgramManager: false,
    appClass: "ProgramManagerApp"
  },
  notepad: { type: "notepad", title: "Notepad", width: 300, height: 200, icon: "notepad", label: "Notepad", executableName: "NOTEPAD.EXE", appClass: "NotepadApp" },
  write: { type: "write", title: "Write", width: 500, height: 400, icon: "write", label: "Write", executableName: "WRITE.EXE", appClass: "WriteApp" },
  codepen: { type: "codepen", title: "CodePen Runner", width: 900, height: 640, icon: "codepen", label: "CodePen", executableName: "CODEPEN.EXE", appClass: "CodePenApp" },
  winfile: { type: "winfile", title: "File Manager", width: 500, height: 350, icon: "winfile", label: "File Mgr", executableName: "WINFILE.EXE", appClass: "FileManagerApp" },
  cardfile: { type: "cardfile", title: "Cardfile", width: 350, height: 400, icon: "cardfile", label: "Cardfile", executableName: "CARDFILE.EXE", appClass: "CardfileApp" },
  calc: { type: "calc", title: "Calculator", width: 220, height: 250, icon: "calc", label: "Calculator", executableName: "CALC.EXE", appClass: "CalcApp" },
  mines: { type: "mines", title: "Minesweeper", width: 240, height: 320, icon: "mines", label: "Minesweeper", executableName: "WINMINE.EXE", appClass: "MinesweeperApp" },
  kakuro: { type: "kakuro", title: "Kakuro", width: 320, height: 380, icon: "kakuro", label: "Kakuro", executableName: "KAKURO.EXE", appClass: "KakuroApp" },
  solitaire: { type: "solitaire", title: "Solitaire", width: 600, height: 450, icon: "solitaire", label: "Solitaire", executableName: "SOL.EXE", appClass: "SolitaireApp" },
  chess: { type: "chess", title: "Chess", width: 640, height: 520, icon: "chess", label: "Chess", executableName: "CHESS.EXE", appClass: "ChessApp" },
  reversi: { type: "reversi", title: "Reversi", width: 300, height: 340, icon: "reversi", label: "Reversi", executableName: "REVERSI.EXE", appClass: "ReversiApp" },
  sudoku: { type: "sudoku", title: "Sudoku", width: 520, height: 620, icon: "sudoku", label: "Sudoku", appClass: "SudokuApp" },
  mafia: { type: "mafia", title: "Mystery Mafia", width: 760, height: 640, icon: "mafia", label: "Mafia", appClass: "MafiaApp" },
  paint: { type: "paint", title: "Paintbrush", width: 500, height: 400, icon: "paint", label: "Paintbrush", executableName: "PBRUSH.EXE", appClass: "PaintApp" },
  pixelstudio: { type: "pixelstudio", title: "Pixel Studio", width: 980, height: 620, icon: "pixelstudio", label: "pixelstudio", appClass: "PixelStudioApp" },
  whiteboard: { type: "whiteboard", title: "Whiteboard", width: 900, height: 640, icon: "whiteboard", label: "whiteboard", appClass: "WhiteboardApp" },
  photoshop: { type: "photoshop", title: "Photoshop 3.0", width: 760, height: 560, icon: "photoshop", label: "Photoshop", executableName: "PHOTOSHP.EXE", appClass: "PhotoshopApp" },
  mplayer: { type: "mplayer", title: "Media Player", width: 350, height: 250, icon: "mplayer", label: "Media Player", executableName: "MPLAYER.EXE", appClass: "MediaPlayerApp" },
  simcity: { type: "simcity", title: "Micropolis", width: 560, height: 520, icon: "simcity", label: "Micropolis", executableName: "SIMCITY.EXE", appClass: "SimCityApp" },
  angrybirds: { type: "angrybirds", title: "Bird Slinger", width: 860, height: 540, icon: "angrybirds", label: "Angry Birds", appClass: "AngryBirdsApp" },
  skifree: { type: "skifree", title: "SkiFree", width: 520, height: 520, icon: "skifree", label: "SkiFree", executableName: "SKIFREE.EXE", appClass: "SkiFreeApp" },
  cannonduel: { type: "cannonduel", title: "Cannon Duel", width: 780, height: 520, icon: "cannonduel", label: "Cannon Duel", appClass: "CannonDuelApp" },
  pinball: { type: "pinball", title: "Pinball", width: 520, height: 640, icon: "pinball", label: "Pinball", executableName: "PINBALL.EXE", appClass: "PinballApp" },
  linerider: { type: "linerider", title: "Line Rider", width: 620, height: 520, icon: "linerider", label: "Line Rider", executableName: "LINERIDR.EXE", appClass: "LineRiderApp" },
  soundrec: { type: "soundrec", title: "Sound Recorder", width: 300, height: 160, icon: "soundrec", label: "Sound Rec", executableName: "SOUNDREC.EXE", appClass: "SoundRecorderApp" },
  radio: { type: "radio", title: "Radio", width: 620, height: 460, icon: "radio", label: "Radio", executableName: "RADIO.EXE", appClass: "RadioApp" },
  beatmaker: { type: "beatmaker", title: "Beat Lab", width: 720, height: 420, icon: "beatmaker", label: "Beat Lab", executableName: "BEATLAB.EXE", appClass: "BeatMakerApp" },
  tracker: { type: "tracker", title: "Chip Studio", width: 820, height: 520, icon: "tracker", label: "Chip Studio", executableName: "TRACKER.EXE", appClass: "TrackerApp" },
  midisequencer: { type: "midisequencer", title: "MIDI Sequencer", width: 920, height: 600, icon: "midisequencer", label: "MIDI Seq", appClass: "MidiSequencerApp" },
  clock: { type: "clock", title: "Clock", width: 250, height: 250, icon: "clock", label: "Clock", executableName: "CLOCK.EXE", appClass: "ClockApp" },
  spotify: { type: "spotify", title: "Spotify", width: 420, height: 520, icon: "spotify", label: "Spotify", executableName: "SPOTIFY.EXE", appClass: "SpotifyApp" },
  charmap: { type: "charmap", title: "Character Map", width: 460, height: 380, icon: "charmap", label: "Char Map", executableName: "CHARMAP.EXE", appClass: "CharMapApp" },
  control: { type: "control", title: "Control Panel", width: 400, height: 300, icon: "control", label: "Control", executableName: "CONTROL.EXE", appClass: "ControlPanelApp" },
  reset: { type: "reset", title: "Reset System", width: 400, height: 260, icon: "reset", label: "Reset", executableName: "RESET.EXE", appClass: "ResetApp" },
  imageviewer: { type: "imageviewer", title: "Image Viewer", width: 720, height: 540, icon: "imageviewer", label: "Image View", executableName: "IMGVIEW.EXE", appClass: "ImageViewerApp" },
  pdfreader: { type: "pdfreader", title: "PDF Reader", width: 720, height: 540, icon: "pdfreader", label: "PDF Reader", appClass: "PdfReaderApp" },
  markdown: { type: "markdown", title: "Markdown Viewer", width: 700, height: 500, icon: "markdown", label: "Markdown", appClass: "MarkdownViewerApp" },
  netnews: { type: "netnews", title: "NetNews", width: 980, height: 640, icon: "netnews", label: "NetNews", appClass: "NetNewsApp" },
  clipbrd: { type: "clipbrd", title: "Clipboard", width: 300, height: 250, icon: "clipboard", label: "Clipboard", executableName: "CLIPBRD.EXE", appClass: "ClipboardApp" },
  taskman: { type: "taskman", title: "Task List", width: 320, height: 350, icon: "taskman", label: "Task List", executableName: "TASKMAN.EXE", appClass: "TaskManApp" },
  database: { type: "database", title: "Data Manager", width: 500, height: 400, icon: "database", label: "Data Mgr", executableName: "DATAMGR.EXE", appClass: "DatabaseApp" },
  postgres: { type: "postgres", title: "Postgres", width: 820, height: 520, icon: "postgres", label: "Postgres", executableName: "POSTGRES.EXE", appClass: "PostgresApp" },
  compiler: { type: "compiler", title: "Tiny C", width: 450, height: 350, icon: "ccompiler", label: "Tiny C", executableName: "TINYC.EXE", appClass: "CompilerApp" },
  python: { type: "python", title: "Tiny Python", width: 450, height: 350, icon: "python", label: "Python", executableName: "PYTHON.EXE", appClass: "PythonApp" },
  console: { type: "console", title: "Console", width: 500, height: 350, icon: "console", label: "Console", executableName: "CONSOLE.EXE", appClass: "ConsoleApp" },
  apiclient: { type: "apiclient", title: "API Client", width: 820, height: 640, icon: "apiclient", label: "API Client", appClass: "ApiClientApp" },
  packetlab: { type: "packetlab", title: "Packet Lab", width: 760, height: 520, icon: "packetlab", label: "Packet Lab", appClass: "PacketLabApp" },
  retroai: { type: "retroai", title: "Retro AI", width: 620, height: 520, icon: "retroai", label: "Retro AI", appClass: "RetroAIApp" },
  hexedit: { type: "hexedit", title: "Hex Editor", width: 720, height: 520, icon: "hexedit", label: "Hex Editor", executableName: "HEXEDIT.EXE", appClass: "HexEditorApp" },
  rss: { type: "rss", title: "RSS Reader", width: 720, height: 520, icon: "rss", label: "RSS Reader", executableName: "RSS.EXE", appClass: "RssApp" },
  browser: { type: "browser", title: "Web Browser", width: 640, height: 480, icon: "browser", label: "Browser", executableName: "WEB.EXE", appClass: "BrowserApp" },
  celeryman: { type: "celeryman", title: "Celery Man", width: 920, height: 640, icon: "celeryman", label: "Celery Man", appClass: "CeleryManApp" },
  vm: { type: "vm", title: "Oriel VM", width: 900, height: 680, icon: "vm", label: "Oriel VM", appClass: "VmApp" },
  radiogarden: { type: "radiogarden", title: "Radio Garden", width: 720, height: 520, icon: "radiogarden", label: "Radio Garden", appClass: "RadioGardenApp" },
  discord: { type: "discord", title: "Discord (API)", width: 720, height: 520, icon: "discord", label: "Discord", executableName: "DISCORD.EXE", appClass: "DiscordApp" },
  bbs: { type: "bbs", title: "BBS Dialer", width: 760, height: 520, icon: "bbs", label: "BBS", appClass: "BbsApp" },
  email: { type: "email", title: "RetroMail", width: 920, height: 640, icon: "email", label: "Mail", appClass: "EmailApp" },
  messenger: { type: "messenger", title: "Messenger", width: 520, height: 420, icon: "messenger", label: "Messenger", appClass: "MessengerApp" },
  irc: { type: "irc", title: "IRC Client", width: 680, height: 500, icon: "irc", label: "IRC", executableName: "IRC.EXE", appClass: "IrcApp" },
  readme: { type: "readme", title: "Read Me", width: 350, height: 400, icon: "readme", label: "Read Me", appClass: "ReadmeApp" },
  doom: { type: "doom", title: "DOOM", width: 640, height: 400, icon: "doom", label: "DOOM", executableName: "DOOM.EXE", appClass: "DoomApp" },
  ti83: { type: "ti83", title: "TI-83 Emulator", width: 620, height: 520, icon: "ti83", label: "TI-83", appClass: "Ti83App" },
  n64: { type: "n64", title: "Nintendo 64", width: 640, height: 520, icon: "n64", label: "N64", appClass: "N64App" },
  minecraft: { type: "minecraft", title: "Minecraft Classic", width: 720, height: 560, icon: "minecraft", label: "Minecraft", executableName: "MCRAFT.EXE", appClass: "MinecraftApp" },
  sandspiel: { type: "sandspiel", title: "Sandspiel", width: 720, height: 560, icon: "sandspiel", label: "Sandspiel", executableName: "SAND.EXE", appClass: "SandspielApp" },
  sandspiel3d: { type: "sandspiel3d", title: "Sandspiel3D", width: 840, height: 620, icon: "sandspiel3d", label: "Sandspiel3D", executableName: "SAND3D.EXE", appClass: "Sandspiel3dApp" },
  shaderlab: { type: "shaderlab", title: "Shader Lab", width: 920, height: 640, icon: "shaderlab", label: "Shader Lab", appClass: "ShaderLabApp" },
  papers: { type: "papers", title: "Checkpoint", width: 640, height: 520, icon: "papers", label: "Checkpoint", appClass: "PapersPleaseApp" }
};

export const APP_DEFINITIONS = Object.values(APP_MANIFEST);

export function getExecutableEntries() {
  return Object.fromEntries(
    APP_DEFINITIONS
      .filter(({ executableName }) => executableName)
      .map(({ executableName, type }) => [executableName, { type: "file", app: type }])
  );
}
